// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.x
// LVGL version: 9.3.0
// Project name: p486panel720
//
// Trimmed starter UI for the Waveshare ESP32-P4-86-Panel (native 720x720).
// Built with alignment-based layout, so it adapts to whatever rotation the
// sketch selects.  DELETE these example files and Export your own "UI files"
// from SquareLine (16-bit color, 720x720, no rotation/offset).

#ifndef _P486PANEL720_UI_H
#define _P486PANEL720_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"

// Builds the UI and loads the first screen.  Called once from the sketch.
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
