/*******************************************************************************
 * ESP32-P4 P486Panel LVGL 9.3 Squareline Launcher
 *
 * For Waveshare ESP32-P4-86-Panel-ETH-2RO
 *
 * Demonstrates touchscreen, LVGL 9.3 and a Squareline Studio UI.
 *
 * LVGL renders at the panel's native 720x720, so Squareline coordinates map
 * 1:1 to pixels -- no scaling.  (For a 480x480 canvas scaled up to this panel,
 * use the sibling library chipguy_P486Panel_480display instead.)
 *
 * Mounting the device rotated?  Uncomment the display.setRotation() line in
 * setup() below.  Touch is transformed to match automatically.  The panel is
 * square, so the Squareline project size stays 720x720 either way.
 *
 * Requires the following libraries:
 *   - chipguy_P486Panel_display  (display driver)
 *   - chipguy_P486Panel_touch    (capacitive touch driver)
 *   - lvgl 9.3
 *
 * Board hardware: 32 MB flash, 32 MB PSRAM
 *
 * Arduino IDE Board Settings:
 *   - Board: ESP32P4 Dev Module
 *   - PSRAM: Enabled
 *   - Flash Size: 32 MegaBytes (256 megabits)
 *   - USB CDC On Boot: Disabled  <- bottom USB-C port (CH340 into UART0)
 *                                  Enabled for the top port (native USB);
 *                                  Enabled costs ~50 KB of internal DRAM.
 *                                  Serial0 is always UART0 = bottom port,
 *                                  whichever way this is set.
 *
 ******************************************************************************/

// This is built for LVGL 9.3, which Squareline can generate UI's for.
// It's important for the version numbers to match, even if it's not newest.
#include "lv_conf.h"
#include "lvgl.h"
#include "lv_setup.hpp"

// Fonts
// The Montserrat font is built into LVGL in multiple sizes, each size takes up memory.
// We enable the 14 point font as a default font.
#define LV_FONT_MONTSERRAT_14 1
// need other sizes?  You'll know if you see compiler errors after trying to
// use them.  Just edit lv_conf.h where FONTs are turned off (0) and turn them on (1)

// The folder of UI files generated by Squareline should be in a subdirectory
// named src in the sketch folder.  The existing files are a small example.
// Simply DELETE all of the example files, and "Export" new "UI files", from Squareline.
// Using the "Arduino TFT_eSPI profile" from Squareline works (among others).
// Required Squareline project settings: 720x720, 16-bit color depth, no
// rotation or offset (this library handles rotation, so keep the Squareline
// project unrotated).
#include "src/ui.h"

void setup() {
    Serial0.begin(115200);

    // Mounted sideways?  Uncomment to rotate the UI 90 degrees so it reads
    // upright, with the USB ports and buttons along the bottom edge where they
    // are least visible.  Accepts 0, 90, 180 or 270.
    // Must be called before begin().
    // display.setRotation(90);

    // Initialize display, touch, and LVGL (touch transform is automatic)
    //
    // NOTE: this call may REBOOT the board once, and that is normal.  Following
    // a warm restart -- ESP.restart(), an OTA reboot, a panic, or a software
    // watchdog reset -- the driver deliberately promotes the soft reset to a
    // deeper system+RTC watchdog reset, to force the LCD to fully reset along
    // with the chip.  A board errata otherwise leaves the panel persistently
    // BLACK after a soft reset: backlight on and firmware running, just no
    // picture, until something resets the RTC domain too.
    //
    // It costs one extra ~1.5 s boot cycle per warm restart, never fires on a
    // cold boot, and is guarded against boot loops.  The catch for your code:
    // whatever setup() did before this line runs AGAIN after the reboot, so
    // don't put must-happen-once side effects above it.
    //
    // See lv_setup.hpp for the details; display.setWarmBootQuiesce(false),
    // called before this line, opts out.
    lv_setup.begin();
    Serial0.printf("LVGL initialized with %dx%d touchscreen (rotated %d degrees)\n",
                   display.width(), display.height(), display.getRotation());

    // Start the Squareline application's own setup
    ui_init();
}


void loop() {
    // Give loop control to LVGL objects created by Squareline application
    lv_timer_handler();
    delay(5);
}
